### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nadheemabd**
Plugin Name Correction

### CODE REVIEW

**Comment by murat-polat** [comment]
Great Job @nadheemabdulla !
Thanks :)

**Comment by nadheemabd** [comment]
Ohh wait.. sorry! 
Please don't merge anything except correction in README.
I was just trying out other things and that was a mistake. I'm sorry for that.

**Comment by nadheemabd** [comment]
I don't actually know if it'll work. I'm just trying out.

**Comment by nadheemabd** [comment]
It does :-)

But the Age and Nationality fields don't actually override the default optional fields. So it'll stay as duplicate.

Screenshot from 2020-12-29 18-16-24

**Comment by murat-polat** [comment]
No problem @nadheemabdulla !
Is it OK now? and works properly? 
Because I have no test server anymore.  You can add/modify more to feature/fields , if you have opportunity. Or you can fork this repo and modify, test that. I think it can be more controlable for you if you wish.. 
Thanks..

**Pull request merged**
